export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const CHAT_ROOMS_SUCCESS = "CHAT_ROOMS_SUCCESS";
export const CHAT_ROOMS_LOADING = "CHAT_ROOMS_LOADING";
export const CHAT_ROOMS_ERROR = "CHAT_ROOMS_ERROR";
export const CURRENT_CHAT_ROOM_SUCCESS = "CURRENT_CHAT_ROOM_SUCCESS";
export const CURRENT_CHAT_ROOM_ERROR = "CURRENT_CHAT_ROOM_ERROR";

export const POST_LOADING = "POST_LOADING";
export const CURRENT_USER_POSTS_SUCCESS = "CURRENT_USER_POSTS_SUCCESS";
export const FOLLOWING_USERS_POSTS_SUCCESS = "FOLLOWING_USERS_POSTS_SUCCESS;";
export const A_USERS_POSTS_SUCCESS = "A_USERS_POSTS_SUCCESS";
export const POST_ERROR = "POST_ERROR";

export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_ERROR = "PROFILE_ERROR";

export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_LOADING = "COMMENT_LOADING";
export const COMMENT_ERROR = "COMMENT_ERROR";
export const COMMENT_LIKE_SUCCESS = "COMMENT_LIKE_SUCCESS";
